### PR TITLE
Exportation of loop as GPX route

### PR DESCRIPTION
**Pull request by GarenKreiz**
New Save button to export a loop once it's been computed. Two GPX routes are generated : one for the loop itself, one from the access to the loop from the center point.

### CODE REVIEW

**Review by pixeye33 — CHANGES_REQUESTED** [review]
Could you add a 
margin-top: 6px;
in
#buttonSaveLoop p ?

**Review by pixeye33 — CHANGES_REQUESTED** [review]
on a small screen the rendering might be improved a bit
image
(iphone 5/SE : 568*320)
Reducing the margin-left on #informationLoop breaks the OK button, but i think the solution is around here.

**Comment by pixeye33** [comment]
Hello,
Thanks for submiting again !

Please consider the requested changes, i see nothing else preventing me to merge it after that :)

**Comment by GarenKreiz** [comment]
Changing the left-margin doesn't do much in my context : fixing the 2nd problem seems to be far beyond my CSS expertise, sorry!

**Comment by pixeye33** [comment]
not a problem, i'll merge it like this, and try to improve on that later.

Thanks for your contribution :)

**Pull request merged**
